# brew install coreutils
command -v gnome-open &> /dev/null && alias open='gnome-open'
command -v gls &> /dev/null && alias ls='gls'

# git aliases
alias add='git add'
alias addp='clear; git add -p'
alias c='gcamstar'
alias ca='gacmstar'
alias cm='gcmstar'
alias d='clear; git diff --color=always'
alias dw='clear; git diff --color=always -w'
alias dwd='clear; git diff --color=always --word-diff'
alias g='git'
alias l='clear; git l ; true'
alias p='git push origin $(git b) 2>&1'
alias pop='git stash pop'
alias s='clear; git status'
alias save='git stash save'
alias show='clear; git show'
alias u='git pull --rebase origin $(git b)'

alias b='build-it'
alias t='test-it'
alias q='test $? -eq 0 && exit'
alias qq='if test $? -eq 0; then say done; exit; else say failure; fi'
alias qqq='sleep 5; q'

# colors!
alias grep='grep -I --color=auto'
alias la='ls -hA  --color --group-directories-first'
alias ll='ls -hlF --color --group-directories-first'
alias bat='bat --theme GitHub'

alias vi=vim
alias gomod='GO111MODULE=on go'
alias https='http --default-scheme=https'
alias spotify="CLIENT_ID=$SPOTIFY_CLIENT_ID CLIENT_SECRET=SPOTIFY_CLIENT_SECRET spotify"
alias swp="find . | grep swp | sed -e 's/.swp//' | sed -e 's/\/\./\//'"
alias tmux='tmux -2'
alias unswp='find . | grep swp | xargs rm'
alias es='exercism submit'
alias notes='vim -c SimplenoteList'
alias worklog='vim -c "SimplenoteOpen d02c9ad65d4747f68cebeefd2f673019" -c on'
alias ok='ok_base $?'
alias copy='pbcopy'
alias gentags='git ls-files | ctags -R --verbose -f .tags'

# Formatters
alias cfmt='clang-format -i -style Google'                                      # C/C++: http://clang.llvm.org/docs/ClangFormat.html
alias dfmt='dub run dfmt -- -i --brace_style=stroustrup --indent_size=2'        # D: https://github.com/dlang-community/dfmt
alias javafmt='java -jar $HOME/.jars/google-java-format-1.5-all-deps.jar -r'    # Java: https://github.com/google/google-java-format
alias jsfmt='prettier --no-semi --write'                                        # JavaScript: https://github.com/prettier/prettier
alias scalafmt='scalafmt -c ~/.scalafmt.conf'                                   # Scala Fmt: http://scalameta.org/scalafmt/
alias scalastyle='scalastyle -c ~/.scalastyle.xml'                              # Scala Style: http://www.scalastyle.org/

# Work
alias bx='bundle exec'
alias derp='PB_IGNORE_DEPRECATIONS=1'
alias localgo='SUBSCRIPTION_PREFIX=marcos-local-go. NATS_HOSTS=nats://sb-sand-gnatsd1:4222 go'
alias mx='cd ~/code/mx/'
alias nats='PB_CLIENT_TYPE=protobuf/nats/client PB_SERVER_TYPE=protobuf/nats/runner'
alias reset-jaeger='docker stop jaeger ; docker rm jaeger ; docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 -p 9411:9411 jaegertracing/all-in-one:1.17'

# Tmux
alias smallest='tmux resize-pane -y 5'
alias smaller='tmux resize-pane -y 10'
alias small='tmux resize-pane -y 25'

# Ruby
alias lrb='rbenvshell $(cat .ruby-version)'
alias jrb='rbenvshell jruby-9.2.6.0'
alias  rb='rbenvshell 2.6.2'
alias fastjruby='JRUBY_OPTS=--debug'
alias rc='derp nats bx rails c'
alias migrate-db='RAILS_ENV=development bx rake db:migrate && RAILS_ENV=test bx rake db:migrate'

# System and networking
alias big-udp='sudo sysctl -w net.inet.udp.maxdgram=65535'
alias more-udp='sudo sysctl -w net.inet.udp.maxdgram=65535'
alias reset-sound='sudo killall coreaudiod'

# Z
function z() {
  _zz $* # z into directory
  cd . # and get cd hooks to run
}

# vi: ft=sh
