# brew install coreutils
command -v gnome-open &> /dev/null && alias open='gnome-open'
command -v gls &> /dev/null && alias ls='gls'

# git
alias addp='git add -p'
alias add='git add'
alias cm='git commit-m'
alias d='git diff --color=always'
alias g='git'
alias l='clear; git l ; true'
alias p='git push origin $(git b) 2>&1'
alias pop='git stash pop'
alias s='git status'
alias save='git stash save'
alias show='git show'

# Pane and process flow helpers
alias q='test $? -eq 0 && exit'
alias qq='if test $? -eq 0; then say done; exit; else say failure; fi'
alias ok='ok_base $?'

# Default flags
alias copy='pbcopy'
alias grep='grep -I --color=auto'
alias ll='ls -hlF --color --group-directories-first'
alias tmux='tmux -2'

# Vim and ctags
alias gentags='git ls-files | ctags -R --verbose -f .tags'
alias swp="find . | grep swp | sed -e 's/.swp//' | sed -e 's/\/\./\//'"
alias unswp='find . | grep swp | xargs rm'
alias vi=vim

# Formatters
alias cfmt='clang-format -i -style Google'                                      # C/C++: http://clang.llvm.org/docs/ClangFormat.html
alias dfmt='dub run dfmt -- -i --brace_style=stroustrup --indent_size=2'        # D: https://github.com/dlang-community/dfmt
alias javafmt='java -jar $HOME/.jars/google-java-format-1.5-all-deps.jar -r'    # Java: https://github.com/google/google-java-format
alias jsfmt='prettier --no-semi --write'                                        # JavaScript: https://github.com/prettier/prettier
alias scalafmt='scalafmt -c ~/.scalafmt.conf'                                   # Scala Fmt: http://scalameta.org/scalafmt/
alias scalastyle='scalastyle -c ~/.scalastyle.xml'                              # Scala Style: http://www.scalastyle.org/

# Work
alias lrb='rbenvshell $(cat .ruby-version)'
alias jrb='rbenvshell jruby-9.2.6.0'
alias rb='rbenvshell 2.7.5'
alias fastjruby='JRUBY_OPTS=--debug'
alias bx='bundle exec'

# System and networking
alias big-udp='sudo sysctl -w net.inet.udp.maxdgram=65535'
alias more-udp='sudo sysctl -w net.inet.udp.maxdgram=65535'
alias reset-sound='sudo killall coreaudiod'

# Tmux
alias smallest='tmux resize-pane -y 5'
alias smaller='tmux resize-pane -y 10'
alias small='tmux resize-pane -y 25'

# Python
alias pipenv-activate='source $(pipenv --venv)/bin/activate'

# Z
function z() {
  _zz $* # z into directory
  cd . # and get cd hooks to run
}

# vi: ft=sh
