# brew install coreutils
command -v gnome-open &> /dev/null && alias open='gnome-open'
command -v gls &> /dev/null && alias ls='gls'

# git aliases
alias add='git add'
alias addp='clear; git add -p'
alias c='gcamstar'
alias ca='gacmstar'
alias cm='gcmstar'
alias d='clear; git diff --color=always'
alias dw='clear; git diff --color=always --word-diff'
alias g='git'
alias l='clear; git l ; true'
alias p='git push origin $(git b) 2>&1'
alias pop='git stash pop'
alias s='clear; git status'
alias save='git stash save'
alias show='clear; git show'
alias u='git pull --rebase origin $(git b)'

alias b='build-it'
alias t='test-it'
alias q='test $? -eq 0 && exit'
alias qq='if test $? -eq 0; then say done; exit; else say failure; fi'
alias lmk='say $(basename $(pwd)) is done'

# colors!
alias grep='grep -I --color=auto'
alias la='ls -hA  --color --group-directories-first'
alias ll='ls -hlF --color --group-directories-first'

alias gomod='GO111MODULE=on go'
alias https='http --default-scheme=https'
alias spotify="CLIENT_ID=$SPOTIFY_CLIENT_ID CLIENT_SECRET=SPOTIFY_CLIENT_SECRET spotify"
alias swp="find . | grep swp | sed -e 's/.swp//' | sed -e 's/\/\./\//'"
alias tmux='tmux -2'
alias unswp='find . | grep swp | xargs rm'
alias es='exercism submit'
alias notes='vim -c SimplenoteList'

# Formatters
alias cfmt='clang-format -i -style Google'                                      # C/C++: http://clang.llvm.org/docs/ClangFormat.html
alias dfmt='dub run dfmt -- -i --brace_style=stroustrup --indent_size=2'        # D: https://github.com/dlang-community/dfmt
alias javafmt='java -jar $HOME/.jars/google-java-format-1.5-all-deps.jar -r'    # Java: https://github.com/google/google-java-format
alias jsfmt='prettier --no-semi --write'                                        # JavaScript: https://github.com/prettier/prettier
alias scalafmt='scalafmt -c ~/.scalafmt.conf'                                   # Scala Fmt: http://scalameta.org/scalafmt/
alias scalastyle='scalastyle -c ~/.scalastyle.xml'                              # Scala Style: http://www.scalastyle.org/

# Work
alias bx='bundle exec'
alias derp='PB_IGNORE_DEPRECATIONS=1'
alias localgo='SUBSCRIPTION_PREFIX=marcos-local-go. NATS_HOSTS=nats://sb-sand-gnatsd1:4222 go'
alias mx='cd ~/code/mx/'
alias nats='PB_CLIENT_TYPE=protobuf/nats/client PB_SERVER_TYPE=protobuf/nats/runner'

# vi: ft=sh
