#!/bin/bash

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

chunkc set global_desktop_offset_top     0
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     0

chunkc set focused_border_color          0xffffffff
chunkc set focused_border_width          0
chunkc set focused_border_outline        0
chunkc set focused_border_skip_floating  1
chunkc set focused_border_skip_monocle   1

chunkc core::load border.so
chunkc core::load tiling.so

chunkc tiling::rule --owner Calculator --state float &
chunkc tiling::rule --owner Calendar   --state float &
chunkc tiling::rule --owner DBeaver    --state float &
chunkc tiling::rule --owner FaceTime   --state float &
chunkc tiling::rule --owner Finder     --state float &
chunkc tiling::rule --owner Mail       --state float &
chunkc tiling::rule --owner Messages   --state float &
chunkc tiling::rule --owner Preview    --state float &
chunkc tiling::rule --owner Slack      --state float &
chunkc tiling::rule --owner Slideshow  --state float &
chunkc tiling::rule --owner Spotify    --state float &
chunkc tiling::rule --owner Todoist    --state float &
chunkc tiling::rule --owner zoom.us    --state float &
