#!/bin/bash

message=$1
branch=`git status | grep "On branch" | head -n1 | sed 's/# On branch //'`

if [ -z $message ]; then
    echo "commit message is required"
    exit 1
elif [ -z $branch ]; then
    echo "invalid branch"
    exit 2
else
    echo commiting and pushing to $branch

    git commit -am "$message"
    git pull --rebase origin $branch

    if [ $? -eq 0 ]; then
        git push origin $branch
        echo
        git log -1 --stat
    fi
fi

