default:
  context:
    class: MyApplication\Tests\Feature\Bootstrap\FeatureContext

  paths:
    features: ../tests/features/

  extensions:
    Behat\MinkExtension\Extension:
      base_url: http://localhost:8080
      goutte: ~
      selenium2:
        wd_host: http://localhost:8643
